Player stats view model
adam-pralat/NBA-STATS-CSC207 pull request #8
Opened 2023-11-20 16:20 UTC by Tonyohcas

2023-11-20 16:54 UTC, jungurilee requested changes
No changes required for the Input Boundary I believe, the interface is for the interactor essentially and doesn't require a return of Output Data. 

void execute() is necessary

2023-11-20 17:33 UTC, RMagill46 approved these changes

2023-11-20 17:33 UTC, jungurilee approved these changes

2023-11-20 17:34 UTC, adam-pralat approved these changes

2023-11-20 17:35 UTC, merged

2023-12-05 03:52 UTC, Tonyohcas reviewed
Understood, the input boundary should be where the request for team stats is being made. It will take the input data and trigger use case execution, so execution is indeed necessary.